#!/usr/bin/env python
"""
capture_datahub_screenshots.py — drive a real DataHub UI and photograph it.

Every image under `docs/screenshots/datahub/` is produced by this script against
a running instance. Nothing is mocked, drawn, or edited. That is the whole point:
a screenshot is only evidence if it can be regenerated by the person doubting it.

    DATAHUB_FRONTEND_URL=http://localhost:9002 \\
    DATAHUB_USER=datahub DATAHUB_PASSWORD=<pw> \\
      python scripts/capture_datahub_screenshots.py --out docs/screenshots/datahub

Honest failure
--------------
A page that cannot be shown is **not** silently skipped and **not** replaced with
a nearby page that happens to load. It is recorded in `MANIFEST.json` with
`captured: false` and the reason, and the reason is what the documentation then
says. A capability matrix that claims a screenshot exists when it does not is
worse than one that admits the gap.

Credentials
-----------
Read from the environment only. The DataHub quickstart's default local
credentials are a well-known development default, not a secret, but they are
still never written into this file — an operator pointing this at a real catalog
must not have a committed password win over their own.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.parse
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

#: Where the pre-installed browser lives in this environment. Playwright's own
#: download is skipped, so the binary must be named explicitly; if it is absent
#: the script says so rather than trying to fetch one.
CHROMIUM_ENV = "DEVGUARD_CHROMIUM_PATH"

DEFAULT_VIEWPORT = {"width": 1680, "height": 1050}


@dataclass
class Shot:
    """One page to photograph."""

    slug: str
    title: str
    #: Path relative to the frontend base URL. `{ds}` is replaced with the
    #: URL-encoded probe dataset URN, `{ml}` with the ML model URN.
    path: str
    #: What a reader should look for. Goes into the manifest and the docs.
    shows: str
    #: Optional CSS selector to wait for before shooting. Without one the shot
    #: can catch a spinner, which is a screenshot of nothing.
    wait_for: Optional[str] = None
    #: Extra settle time in ms for graph canvases that animate into place.
    settle_ms: int = 2500
    full_page: bool = True
    #: Optional selectors to click before shooting, in order (tab switches,
    #: toggles, filter menus). A failed click is recorded, never fatal.
    click: Optional[str] = None
    clicks: tuple[str, ...] = ()


@dataclass
class Capture:
    slug: str
    title: str
    url: str
    shows: str
    captured: bool
    file: Optional[str] = None
    bytes: int = 0
    reason: str = ""
    console_errors: list[str] = field(default_factory=list)
    # Stamped per shot, not per run. A `--only` re-shoot merges into the
    # existing manifest, so a single run-level timestamp would re-date every
    # row it did not actually take.
    captured_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat())


def write_manifest(out: Path, captures: list[Capture], *, merge: bool,
                   **meta) -> int:
    """Write MANIFEST.json, merging into any existing one on a partial run.

    A `--only` run MERGES instead of replacing. Replacing made the manifest lie:
    re-shooting two panels rewrote the file to describe two captures while
    twenty-three PNGs sat in the directory, and the manifest is what the docs
    index is generated from. A record of what is on disk that disagrees with
    what is on disk is worse than no record. The same applies when a partial run
    dies at login — that path must not clobber a full manifest either.

    Returns the number of rows the written manifest describes.
    """
    rows: dict[str, dict] = {}
    path = out / "MANIFEST.json"
    if merge and path.is_file():
        try:
            previous = json.loads(path.read_text(encoding="utf-8"))
            # Manifests written before shots were stamped individually carry
            # only a run-level time. Backfill it so a re-shoot cannot leave the
            # file claiming to be newer than the rows it kept.
            inherited = previous.get("captured_at")
            for row in previous.get("captures") or []:
                if row.get("slug"):
                    row.setdefault("captured_at", inherited)
                    rows[row["slug"]] = row
        except (OSError, json.JSONDecodeError) as exc:
            print(f"  note    could not merge the existing manifest ({exc}); "
                  "writing only this run's captures")
    for capture in captures:
        rows[capture.slug] = capture.__dict__

    # Ordered by the canonical shot list, so the file reads in the same order the
    # docs present it regardless of which subset was last re-shot.
    order = {shot.slug: i for i, shot in enumerate(shots())}
    ordered = sorted(rows.values(),
                     key=lambda r: order.get(r.get("slug", ""), len(order)))
    # The newest capture the manifest describes — which equals the run time on a
    # full run, and stays true on a merged one. Per-shot times are on each row.
    stamps = [r["captured_at"] for r in ordered if r.get("captured_at")]
    path.write_text(json.dumps({
        "captured_at": max(stamps) if stamps else
                       datetime.now(timezone.utc).isoformat(),
        "manifest_written_at": datetime.now(timezone.utc).isoformat(),
        **meta,
        "captures": ordered,
    }, indent=2), encoding="utf-8")
    return len(ordered)


def shots() -> list[Shot]:
    """The capture list, in the order the docs present them."""
    return [
        Shot("01-login", "Login",
             "/login",
             "The DataHub sign-in page this session authenticated against.",
             wait_for="input[data-testid='username'], input#username, input[name='username']",
             settle_ms=1200, full_page=False),
        Shot("02-home", "Home",
             "/",
             "The authenticated landing page: platform tiles and entity counts "
             "for the catalog this session ingested.",
             wait_for="text=/Datasets|Explore|Welcome/i"),
        Shot("03-search", "Search",
             "/search?query=%2A",
             "Free-text search across all entity types, with the facet rail "
             "DataHub builds from the live index.",
             wait_for="text=/result|Filter/i"),
        Shot("04-browse", "Browse",
             "/browse/dataset",
             "Hierarchical browse paths, derived by DataHub from the ingested "
             "platform/database/schema structure.",
             wait_for="text=/postgres|dbt|Platform/i"),
        Shot("05-dataset", "Dataset",
             "/dataset/{ds}/",
             "A dataset entity page: platform, description, owners, tags and "
             "domain, all read from the catalog.",
             wait_for="text=/Schema|Documentation|Lineage/i"),
        Shot("06-dataset-schema", "Dataset schema",
             "/dataset/{ds}/Schema",
             "The schema DataHub holds for the dataset — field paths, native "
             "types and nullability as ingested from Postgres.",
             wait_for="text=/Field|Type/i"),
        # The three graph shots collapse the entity sidebar first. It occupies
        # roughly a quarter of the viewport, and the graph does not reflow into
        # the space it leaves — so without this the lineage of five nodes is
        # rendered into a strip and is unreadable at the size a README embeds it.
        Shot("07-dataset-lineage", "Lineage graph",
             "/dataset/{ds}/Lineage",
             "The lineage graph: stg_users and stg_orders into the feature "
             "table, then through the training job to the churn model. Every "
             "edge was ingested from the running stack; none was hand-authored.",
             wait_for="[data-testid^='unexpanded-lineage-card']",
             click="[data-testid='entity-sidebar-collapse-tab']",
             settle_ms=5000, full_page=False),
        Shot("08-column-lineage", "Column lineage",
             "/dataset/{ds}/Lineage",
             "The same graph with column detail expanded — the field-level "
             "mapping DataHub's dbt source derived from the manifest dbt "
             "itself produced.",
             wait_for="[data-testid='expand-contract-columns']",
             click="[data-testid='expand-contract-columns']",
             settle_ms=5000, full_page=False),
        Shot("09-impact-analysis", "Impact analysis",
             "/dataset/{ds}/Lineage",
             "DataHub's own impact analysis over the same graph DevGuard's "
             "Pathfinder walks for blast radius.",
             wait_for="text=/Impact Analysis/i",
             click="text=/Impact Analysis/i", settle_ms=5000, full_page=False),
        Shot("10-dataset-stats", "Dataset profile / stats",
             "/dataset/{ds}/Stats",
             "Dataset profile: row and column counts and per-column statistics, "
             "profiled from the live database during ingestion.",
             wait_for="text=/Stats|Rows|Column|Profil/i", settle_ms=4000),
        Shot("11-dataset-quality", "Assertions / quality",
             "/dataset/{ds}/Quality",
             "The assertions surface DevGuard's Referee reads for independent "
             "recovery corroboration.",
             wait_for="text=/Assertion|Quality|Validation/i", settle_ms=4000),
        Shot("12-domains", "Domains",
             "/domains",
             "Domains — the governance grouping DevGuard resolves alongside "
             "ownership.",
             wait_for="text=/Domain/i"),
        Shot("13-glossary", "Business glossary",
             "/glossary",
             "The business glossary as this instance holds it.",
             wait_for="text=/Glossary|Term/i"),
        Shot("14-tags", "Tags",
             "/search?query=%2A&filter__entityType___false___EQUAL___0=TAG",
             "Tag entities, including `devguard_incident_impacted`. That one is "
             "provisioned by scripts/provision_catalog.py, not minted by the "
             "agent: `add_tags` fails against a tag URN that does not exist, and "
             "the Scribe deliberately does not create one.",
             wait_for="text=/Tag|result/i"),
        Shot("15-policies", "Policies",
             "/settings/permissions/policies",
             "The policy list DevGuard's least-privilege service account is "
             "scoped by.",
             wait_for="text=/Polic/i", settle_ms=3500),
        Shot("16-ml-model", "ML model metadata",
             "/mlModels/{ml}/",
             "The ML model at the end of the blast radius, read as an entity "
             "rather than counted as a URN.",
             wait_for="text=/Model|Feature|Training/i", settle_ms=3500),
        Shot("17-ingestion", "Ingestion sources",
             "/ingestion",
             "DataHub's ingestion surface. The substrate was ingested with the "
             "committed recipes rather than through this screen, so this shows "
             "the platform capability, not the path used.",
             wait_for="text=/Ingestion|Source/i", settle_ms=3000),
        Shot("18-analytics", "Analytics",
             "/analytics",
             "DataHub's built-in usage analytics over this instance.",
             wait_for="text=/Analytic|Chart|Section/i", settle_ms=4000),

        # --- what DevGuard wrote back -------------------------------------
        # These five are the other half of the integration. Everything above is
        # DataHub showing what was ingested; these are DataHub showing what the
        # agent put there after a verified recovery — the loop's output, read
        # from the catalog by the same UI a human would use.
        # The Resolved filter is opened deliberately. DataHub's Incidents tab
        # defaults to ACTIVE only, and a correctly-finished DevGuard run leaves
        # nothing active — so the default view of a *successful* run is an empty
        # table, which is the least informative possible screenshot of the thing
        # that worked.
        Shot("19-writeback-incident", "Write-back — incident",
             "/dataset/{wb}/Incidents",
             "Artifact 1: the incident DevGuard raised on detection and resolved "
             "only after the Referee verified the fix. Filtered to Resolved, "
             "because a completed run leaves no active incident behind.",
             wait_for="text=/Incident/i",
             clicks=("text=/^Filter/", "text=/^State$/", "text=/^Resolved$/"),
             settle_ms=4000),
        Shot("20-writeback-column", "Write-back — column annotation",
             "/dataset/{wb}/Schema",
             "Artifact 3: the column-level tag and description written back to "
             "the exact field the incident was about.",
             wait_for="text=/user_id|customer_id/i", settle_ms=4000),
        # The `devguard` group renders collapsed, and it is the only part of
        # this page the write-back produced — the rest is dbt's own manifest
        # metadata. Expanding it is the difference between a screenshot of
        # artifact 4 and a screenshot of dbt.
        Shot("21-writeback-properties", "Write-back — structured properties",
             "/dataset/{wb}/Properties",
             "Artifact 4: structured incident facts — verified_at and "
             "last_incident_id — written as typed catalog values rather than "
             "prose, under the `devguard` namespace.",
             wait_for="text=/Propert/i",
             # The row-expand chevron, not the group's label — clicking the text
             # selects it and leaves the group collapsed.
             clicks=(".anticon-right",), settle_ms=4000),
        Shot("22-writeback-governance", "Write-back — governance tab",
             "/dataset/{wb}/Governance",
             "The governance surface of the dataset the agent wrote to, showing "
             "owners, terms and domain alongside the agent's own annotations.",
             wait_for="text=/Owner|Domain|Governance/i", settle_ms=4000),
        Shot("23-writeback-dataset", "Write-back — dataset overview",
             "/dataset/{wb}/",
             "The whole picture on the incident's dataset after a complete run.",
             wait_for="text=/Schema|Lineage/i", settle_ms=4000),
    ]


#: DataHub greets a fresh profile with a product tour — a modal plus a dimming
#: backdrop that lands on top of the very panels these screenshots exist to
#: show. It is dismissed rather than photographed: a screenshot of DataHub's
#: onboarding is not evidence of DataHub's lineage.
_OVERLAY_CLOSERS = (
    "button[aria-label='close']",
    ".ant-modal-close",
    ".ant-tour-close",
    "[data-testid='onboarding-close']",
    "button:has-text('Skip')",
)


def dismiss_overlays(page) -> None:
    """Close any tour/modal, then confirm the dimming backdrop is gone.

    Runs before every shot, not once after login: the tour is step-based and
    re-arms on pages the profile has not visited yet, so dismissing it on the
    home page does not dismiss it on the lineage tab.
    """
    for _ in range(4):
        closed = False
        for selector in _OVERLAY_CLOSERS:
            try:
                node = page.query_selector(selector)
                if node and node.is_visible():
                    node.click(timeout=3000)
                    closed = True
                    page.wait_for_timeout(400)
            except Exception:  # noqa: BLE001 — best effort by design
                pass
        if not closed:
            break
    try:
        page.keyboard.press("Escape")
    except Exception:  # noqa: BLE001
        pass
    # The backdrop outlives the modal by an animation frame; waiting for it to
    # detach is what stops a dimmed screenshot.
    try:
        page.wait_for_selector(".ant-modal-mask, .ant-tour-mask",
                               state="detached", timeout=4000)
    except Exception:  # noqa: BLE001
        pass


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="docs/screenshots/datahub")
    ap.add_argument("--dataset-urn", default=os.environ.get("DEVGUARD_PROBE_DATASET", ""))
    ap.add_argument("--ml-model-urn", default=os.environ.get("DEVGUARD_PROBE_MLMODEL", ""))
    ap.add_argument("--writeback-urn", default=os.environ.get("DEVGUARD_WRITEBACK_DATASET", ""),
                    help="The dataset DevGuard wrote back to. Its shots are skipped "
                         "when absent rather than pointed at a dataset the agent "
                         "never touched.")
    ap.add_argument("--only", default="", help="Comma-separated slugs to capture")
    args = ap.parse_args()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("playwright is not installed: pip install playwright", file=sys.stderr)
        return 2

    base = (os.environ.get("DATAHUB_FRONTEND_URL") or "http://localhost:9002").rstrip("/")
    user = os.environ.get("DATAHUB_USER") or "datahub"
    password = os.environ.get("DATAHUB_PASSWORD") or ""
    if not password:
        print("DATAHUB_PASSWORD is not set. Refusing to guess a credential.",
              file=sys.stderr)
        return 2

    chromium_path = os.environ.get(CHROMIUM_ENV) or None
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    ds = urllib.parse.quote(args.dataset_urn, safe="")
    ml = urllib.parse.quote(args.ml_model_urn, safe="")
    wb = urllib.parse.quote(args.writeback_urn, safe="")

    wanted = {s.strip() for s in args.only.split(",") if s.strip()}
    plan = [s for s in shots() if not wanted or s.slug in wanted]
    if not args.dataset_urn:
        plan = [s for s in plan if "{ds}" not in s.path]
    if not args.ml_model_urn:
        plan = [s for s in plan if "{ml}" not in s.path]
    if not args.writeback_urn:
        plan = [s for s in plan if "{wb}" not in s.path]

    captures: list[Capture] = []

    with sync_playwright() as p:
        launch: dict = {"args": ["--no-sandbox", "--disable-dev-shm-usage"]}
        if chromium_path:
            launch["executable_path"] = chromium_path
        browser = p.chromium.launch(**launch)
        context = browser.new_context(viewport=DEFAULT_VIEWPORT, device_scale_factor=1)
        page = context.new_page()

        errors: list[str] = []
        page.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)

        # --- login, captured before it is used ------------------------------
        login_shot = next((s for s in plan if s.slug == "01-login"), None)
        page.goto(f"{base}/login", wait_until="domcontentloaded", timeout=60000)
        page.wait_for_timeout(2500)
        if login_shot:
            f = out / f"{login_shot.slug}.png"
            page.screenshot(path=str(f))
            captures.append(Capture(login_shot.slug, login_shot.title,
                                    f"{base}/login", login_shot.shows, True,
                                    f.name, f.stat().st_size))
            print(f"  ok      {login_shot.slug}")

        try:
            page.fill("input[data-testid='username'], input#username, "
                      "input[name='username']", user)
            page.fill("input[data-testid='password'], input#password, "
                      "input[name='password']", password)
            # `data-testid='sign-in'` and nothing looser. A `:has-text('Sign
            # In')` fallback matches DataHub's **"Sign in with SSO"** button,
            # which navigates nowhere on a quickstart with no IdP configured —
            # the run then dies on a navigation timeout that looks like a bad
            # password.
            page.click("button[data-testid='sign-in']")
            page.wait_for_url(lambda u: "/login" not in u, timeout=45000)
            page.wait_for_timeout(4000)
            dismiss_overlays(page)
            print(f"  ok      authenticated as {user}")
        except Exception as exc:  # noqa: BLE001
            print(f"FATAL: login failed: {type(exc).__name__}: {exc}", file=sys.stderr)
            write_manifest(out, captures, merge=bool(wanted),
                           frontend=base, login_failed=str(exc))
            browser.close()
            return 2

        for shot in plan:
            if shot.slug == "01-login":
                continue
            url = base + (shot.path.replace("{ds}", ds)
                          .replace("{ml}", ml).replace("{wb}", wb))
            errors.clear()
            try:
                page.goto(url, wait_until="domcontentloaded", timeout=60000)
                if shot.wait_for:
                    try:
                        page.wait_for_selector(shot.wait_for, timeout=20000)
                    except Exception:
                        # A missing marker is not fatal — the page may render the
                        # same information under different copy. It is recorded.
                        errors.append(f"marker not found: {shot.wait_for}")
                for selector in ([shot.click] if shot.click else []) + list(shot.clicks):
                    try:
                        page.click(selector, timeout=8000)
                        page.wait_for_timeout(1200)
                    except Exception as exc:  # noqa: BLE001
                        errors.append(f"click {selector!r} failed: {exc}")
                page.wait_for_timeout(shot.settle_ms)
                dismiss_overlays(page)
                page.wait_for_timeout(600)
                f = out / f"{shot.slug}.png"
                page.screenshot(path=str(f), full_page=shot.full_page)
                size = f.stat().st_size
                captures.append(Capture(shot.slug, shot.title, url, shot.shows,
                                        True, f.name, size,
                                        console_errors=errors[:5]))
                print(f"  ok      {shot.slug:22} {size:>8} bytes")
            except Exception as exc:  # noqa: BLE001
                captures.append(Capture(shot.slug, shot.title, url, shot.shows,
                                        False, reason=f"{type(exc).__name__}: {exc}",
                                        console_errors=errors[:5]))
                print(f"  FAILED  {shot.slug:22} {type(exc).__name__}: {exc}")

        browser.close()

    listed = write_manifest(
        out, captures, merge=bool(wanted),
        frontend=base,
        dataset_urn=args.dataset_urn,
        ml_model_urn=args.ml_model_urn,
        writeback_urn=args.writeback_urn,
        viewport=DEFAULT_VIEWPORT,
        partial_run=sorted(wanted) if wanted else None,
    )

    ok = sum(1 for c in captures if c.captured)
    print(f"\n  {ok}/{len(captures)} captured → {out}"
          f"{f' (manifest now lists {listed})' if wanted else ''}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
